# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repo:
    description: 'Repository URL'
    required: true
    default: 'https://github.com/percona/pmm-doc'
  release_tag:
    description: 'Repository URL'
    required: true
outputs:
  changelog:
    description: 'The generated changelog'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ github.ref_name }}
