name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: pmm_release
        shell: bash
        run: |
          version="${release_tag/refs\/tags\/v/}"
          echo "::set-env PMM_RELEASE_VERSION::$version"
        env:
          release_tag: ${{ github.ref }}
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          body_path: https://raw.githubusercontent.com/percona/pmm-doc/main/docs/release-notes/$PMM_RELEASE_VERSION.md
