name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: pmm_release
        shell: bash
        run: |
          git clone --depth 1 https://github.com/percona/pmm-doc doc
          cd doc/docs/release-notes
          version="${release_tag/refs\/tags\/v//}"
          cat ./$version.md > ${{ github.workspace }}-CHANGELOG.txt
        env:
          release_tag: ${{ github.ref }}
      - name: echo
        shell: bash
        run: |
          echo "${{ env.CHANGELOG }}"
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
